### ISSUE TITLE
Problem with ansible (on vagrant)

### ISSUE THREAD

**Issue by nmabhinandan** [constabulary/gb#576]
I'm trying to install the dependencies of my project as part of vagrant provisioning using ansible. It looks something like this.

```yaml
- name: Fetch vendored packages
  shell: "{{ go_path + '/bin/gb vendor restore' }}"
  args:
    chdir: "/vagrant"
  environment:
    GOPATH: "{{ go_path }}"
```

And I'm getting this error
```json
fatal: [default]: FAILED! => {
   "changed":true,
   "cmd":"/home/vagrant/go/bin/gb vendor restore",
   "delta":"0:00:00.028102",
   "end":"2016-02-28 08:30:06.805461",
   "failed":true,
   "rc":2,
   "start":"2016-02-28 08:30:06.777359",
   "stderr":"FATAL: unknown command \"vendor\"\ngb, a project based build tool for the Go programming language.\n\nUsage:\n\n        gb command [arguments]\n\nThe commands are:\n\n        build       build a package\n        doc         show documentation for a package or symbol\n        env         print project environment variables\n        generate    generate Go files by processing source\n        info        info returns information about this project\n        list        list the packages named by the importpaths\n        test        test packages\n\nUse \"gb help [command]\" for more information about a command.\n\nAdditional help topics:\n\n        plugin      plugin information\n        project     gb project layout\n\nUse \"gb help [topic]\" for more information about that topic.",
   "stdout":"",
   "stdout_lines":[

   ],
   "warnings":[

   ]
}
```
